### ISSUE TITLE
[Feature] Add an address list

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/NosoSova#27]
Hey Andrii(@pasichDev),

It would be nice to have an address list so we don't have to copy paste outgoing addresses all the time.

Cheers,
Gus

**Comment by pasichDev** [comment]
Hi @gcarreno what do you mean?

**Comment by pasichDev** [comment]
Hi, @gcarreno !

Resolved: Add a contract book and save the latest payments. 

You can add addresses and owner information to the contact book.

@pasichDev

**Comment by gcarreno** [comment]
Jey Andrii(@pasichDev),

That's bloody awesome!!!

As usual, you demonstrate the professionalism that you have!!!

Cheers,
Gus

**Comment by pasichDev** [comment]
@gcarreno It's settled! So I'm closing this issue!

**Comment by gcarreno** [comment]
Hey Andrii(@pasichDev)

Awesome!! Thanks!! :people_hugging: 

Cheers,
Gus
